
stages:
  - test

test-similarity-debian-buster-python3.7:
  image: gitdocker.physik.hu-berlin.de/sol/exciting:debian-buster-GCC8
  #image: gitdocker.physik.hu-berlin.de/kuban/similarity-data-framework:debian-buster-python3.7
  stage: test
  tags: 
    - docker
  before_script:
    - apt-get --allow-releaseinfo-change update && apt-get install -y libpython3.7 libpython3.7-dev python3-pip
    - pip3 install --upgrade pip
    - pip3 install numpy
    - pip3 install -e .
  script:
    - pytest tests/test_self.py tests/test_SimilarityMatrix.py
