stages:
  - test

test-similarity-debian-buster-python3.7:
  image: gitdocker.physik.hu-berlin.de/kuban/similarity-data-framework:debian-buster-python3.7
  stage: test
  tags: 
    - docker
  script:
    - python unit_tests.py
