stages:
  - test

test-similarity-debian-buster-python3.7:
  image: gitdocker.physik.hu-berlin.de/kuban/similarity-data-framework:debian-buster-python3.7
  stage: test
  tags: 
    - docker
  before_script:
    - apt-get install -y libpython3.7 libpython3.7-dev python3-pip
    - pip3 install -e simdatframe
  script:
    - python3 unit_tests.py
