image: python:3.10

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

full_test:
  stage: test
  before_script:
    - pip3 install --upgrade pip
    - pip3 install pytest
    - pip3 install --upgrade build
    - python -m build
    - pip3 install dist/madas-*-py3-none-any.whl
    - mkdir runtests && cd runtests
  script:
    - pytest -vv ../tests
    - pytest -vv ../dependencies/dos-fingerprints/tests
