image: python:3.10

stages:
  - test

full_test:
  stage: test
  before_script:
    - pip3 install --upgrade pip
    - pip3 install pytest
    - pip3 install .
    - python -c "import madas; print(madas.__version__)"
  script:
    - pytest -vv tests
