image: python:3.10

stages:
  - test

install:
  stage: test
  before_script:
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install .
  script:
    - pytest -vv tests
