image: python:3.10

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

full_test:
  stage: test
  before_script:
    - pip3 install --upgrade pip
    - pip3 install pytest
    - pip3 install .
  script:
    - pytest -vv tests
