image: python:3.10

stages:
  - test

install:
  stage: test
  before_script:
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install .
  script:
    - pytest tests


#test-similarity-debian-buster-python3.7:
#  image: gitdocker.physik.hu-berlin.de/sol/exciting:debian-buster-GCC8
#  #image: gitdocker.physik.hu-berlin.de/kuban/similarity-data-framework:debian-buster-python3.7
#  stage: test
#  tags: 
#    - docker
#  before_script:
#    - apt-get --allow-releaseinfo-change update && apt-get install -y python3.10 libpython3.10 libpython3.10-dev python3-pip
#    - pip3 install --upgrade pip
#    - pip3 install numpy
#    - pip3 install jsonschema==3.2.0
#    - pip3 install -r requirements.txt
#    - pip3 install -e .
#  script:
#    - pytest tests
